version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app/graphql-playground:delegated
    ports:
      - "${HTTP_PORT:-8000}:${HTTP_PORT:-8000}"
    command: npm start
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgis://postgres:postgres@postgres:5432
  postgres:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata:
