version: "3.9"
services:
  full:
    image: apollo-full
    build:
      context: ./full
      dockerfile: Dockerfile
    volumes:
      - ./full:/app/full:delegated
    ports:
      - "8000:8000"
    command: npm start
    depends_on:
      - postgres
    links:
      - postgres
  # apollo:
  #   image: apollo-app
  #   build:
  #     context: ./react-graphql-github-apollo-starter-kit
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./react-graphql-github-apollo-starter-kit:/app/react-graphql-github-apollo-starter-kit:delegated
  #   ports:
  #     - "${HTTP_PORT:-8001}:${HTTP_PORT:-8000}"
  #     - "4001:3000"
  #     - "82:80"
  #   command: npm start
  # minimal:
  #   image: minimal-node-app
  #   build:
  #     context: ./minimal-node-application
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./minimal-node-application:/app/minimal-node-application:delegated
  #   ports:
  #     - "${HTTP_PORT:-8001}:${HTTP_PORT:-8000}"
  #     - "4000:3000"
  #     - "81:80"
  #   command: npm start
  # node-server:
  #   image: nodejs-graphql-and-apollo-server
  #   build:
  #     context: ./nodejs-graphql-and-apollo-server
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./nodejs-graphql-and-apollo-server:/app/nodejs-graphql-and-apollo-server:delegated
  #   ports:
  #     - "${HTTP_PORT:-8001}:${HTTP_PORT:-8000}"
  #     - "4000:3000"
  #     - "81:80"
  #   command: npm start
  # web:
  #   build:
  #     context: ./react-graphql-github-vanilla
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./react-graphql-github-vanilla:/app/graphql-playground:delegated
  #   ports:
  #     - "${HTTP_PORT:-8000}:${HTTP_PORT:-8000}"
  #     - "3000:3000"
  #     - "80:80"
  #   command: npm start
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DATABASE_URL=postgis://postgres:postgres@postgres:5432
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  pgdata:
  full:
