version: "3.9"
services:
  minimal:
    image: minimal-node-app
    build:
      context: ./minimal-node-application
      dockerfile: Dockerfile
    volumes:
      - ./minimal-node-application:/app/minimal-node-application:delegated
    ports:
      - "${HTTP_PORT:-8001}:${HTTP_PORT:-8000}"
      - "4000:3000"
      - "81:80"
    command: npm start
  web:
    build:
      context: ./react-graphql-github-vanilla
      dockerfile: Dockerfile
    volumes:
      - ./react-graphql-github-vanilla:/app/graphql-playground:delegated
    ports:
      - "${HTTP_PORT:-8000}:${HTTP_PORT:-8000}"
      - "3000:3000"
      - "80:80"
    command: npm start
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgis://postgres:postgres@postgres:5432
  postgres:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pgdata:
